/**
 * Test Videos Page
 * Displays visual testing recordings from Playwright MCP
 */

import './TestVideos.css';

interface VideoCardProps {
  title: string;
  meta: string;
  videoSrc: string;
}

function VideoCard({ title, meta, videoSrc }: VideoCardProps) {
  return (
    <div className="video-card">
      <div className="video-title">{title}</div>
      <div className="video-meta">{meta}</div>
      <video controls preload="metadata">
        <source src={`/test-videos/${videoSrc}`} type="video/webm" />
        Your browser doesn't support video playback.
      </video>
      <div className="video-links">
        <a href={`/test-videos/${videoSrc}`} className="btn btn-primary" download>
          ⬇️ Download
        </a>
        <a href={`/test-videos/${videoSrc}`} className="btn btn-secondary" target="_blank" rel="noopener noreferrer">
          🔗 Open
        </a>
      </div>
    </div>
  );
}

export function TestVideos() {
  return (
    <div className="test-videos-container">
      <h1>🎬 Hexhaven Test Videos</h1>
      <p className="subtitle">Visual testing recordings from Playwright MCP</p>

      <div className="stats">
        <div className="stat">
          <div className="stat-value">6</div>
          <div className="stat-label">Total Videos</div>
        </div>
        <div className="stat">
          <div className="stat-value">6.1 MB</div>
          <div className="stat-label">Total Size</div>
        </div>
        <div className="stat">
          <div className="stat-value">Firefox</div>
          <div className="stat-label">Browser</div>
        </div>
      </div>

      <div className="video-grid">
        <VideoCard
          title="📋 Comprehensive Game Flow"
          meta="2.4 MB • Full game flow test (3 minutes)"
          videoSrc="video.webm"
        />
        <VideoCard
          title="✨ MCP Visual Test (Latest)"
          meta="562 KB • Game creation with accessibility analysis"
          videoSrc="2ece540f-6e49-4f3f-b564-2d830bdf6049.webm"
        />
        <VideoCard
          title="✨ MCP Visual Test (Run 2)"
          meta="172 KB • Quick game creation test"
          videoSrc="a92ca52e-b584-4612-94d2-d3fb382d2c34.webm"
        />
        <VideoCard
          title="📦 Archived: Comprehensive Flow"
          meta="2.4 MB • Earlier comprehensive test run"
          videoSrc="comprehensive-game-flow-Co-024cc-from-creation-to-monster-AI-firefox_video_20251201_033016.webm"
        />
        <VideoCard
          title="📦 Archived: MCP Session 1"
          meta="562 KB • Archived MCP test run"
          videoSrc="mcp-session_2ece540f-6e49-4f3f-b564-2d830bdf6049_20251201_033017.webm"
        />
        <VideoCard
          title="📦 Archived: MCP Session 2"
          meta="172 KB • Archived quick test"
          videoSrc="mcp-session_a92ca52e-b584-4612-94d2-d3fb382d2c34_20251201_033016.webm"
        />
      </div>

      <footer className="test-videos-footer">
        <p>Generated by Playwright MCP Visual Testing • Firefox ARM64 Headless</p>
        <p>
          <a href="/">← Back to Hexhaven</a>
        </p>
      </footer>
    </div>
  );
}
